name: CI Simples

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixar o código do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2. Executar um comando simples (teste inicial)
      - name: Teste de funcionamento
        run: echo "CI funcionando no projeto INPE!"
