name: CI Simples
on:
push:
branches: [ dev ] # dispara apenas quando o commit é na branch dev
pull_request:
branches: [ dev ] # dispara quando há PR para dev
jobs:
build:
runs-on: ubuntu-latest # ambiente que o GitHub usa (máquina Linux)
steps:
- name: Checkout do repositório
uses: actions/checkout@v4
- name: Teste de funcionamento
run: echo "CI funcionando no projeto INPE!"
